version: '3'
services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec jekyll serve --host '0.0.0.0'"
    volumes:
      - .:/website-reboot
    ports:
      - "4000:4000"
