name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle install
    - run: bundle exec jekyll build
    - run: cd _site && git init
    - run: cd _site && git config user.email "${{ github.actor }}@users.noreply.github.com"
    - run: cd _site && git config user.name "${{ github.actor }}"
    - run: cd _site && git add .
    - run: cd _site && git commit -m'deploy'
    - run: cd _site && git push -f "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git" master:gh-pages
